Repository Shabaldas/storm_esbuild, pull requests merged in 2023-04, with the labels that each got.

#84 (feat): remove broken rspec from dummy folder
  .gitignore
  .rubocop.yml
  spec/lib/database_seeds/dummy/product_categories_seed_spec.rb
Labels: bug

#87 [FEATURE] Add new Admin dashborad
  app/views/admin/dashboard/index.html.erb
  spec/rails_helper.rb
  spec/request/admin/dashboard_spec.rb
Labels: ruby

#61 Uppdate sign in, sign up, forgot password and edit user pages
  app/assets/stylesheets/application.tailwind.css
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/layouts/application.html.erb
  app/views/products/_products.html.erb
  app/views/products/_store_filter.html.erb
  app/views/products/index.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_header.html.erb
  app/views/static_pages/home.html.erb
  config/environments/development.rb
  package.json
  tailwind.config.js
  yarn.lock
Labels: enhancement

#91 Add products index to admin panel
  app/controllers/admin/products_controller.rb
  app/views/admin/_header.html.erb
  app/views/admin/dashboard/index.html.erb
  app/views/admin/products/_product.html.erb
  app/views/admin/products/index.html.erb
  app/views/layouts/admin.html.erb
  config/routes.rb
  package.json
  spec/request/admin/dashboard_spec.rb
  spec/request/admin/products_spec.rb
  tailwind.config.js
  yarn.lock
Labels: ruby

#93 (feat): remove not using method in helper
  app/helpers/application_helper.rb
Labels: ruby

#95 (feat): add pagy gem, pagination to admin panel
  Gemfile
  Gemfile.lock
  app/controllers/admin/product_categories_controller.rb
  app/controllers/admin/products_controller.rb
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  app/views/admin/product_categories/index.html.erb
  app/views/admin/products/index.html.erb
  config/initializers/pagy.rb
  spec/rails_helper.rb
Labels: ruby

#98 (feature): add admin product show page, with available colors
  app/assets/stylesheets/application.tailwind.css
  app/assets/stylesheets/components/typography.css
  app/controllers/admin/products_controller.rb
  app/helpers/product_helper.rb
  app/models/product.rb
  app/views/admin/product_categories/index.html.erb
  app/views/admin/products/_product.html.erb
  app/views/admin/products/index.html.erb
  app/views/admin/products/new.html.erb
  app/views/admin/products/show.html.erb
  app/views/layouts/admin.html.erb
  config/routes.rb
  spec/request/admin/products_spec.rb
  tailwind.config.js
Labels: ruby, css

#99 (feature): admin product show page, with available sizes
  app/models/product.rb
  app/views/admin/products/show.html.erb
Labels: ruby, css
