Repository Shabaldas/storm_esbuild, pull requests merged in 2023-07, with the labels that each got.

#169 STORM_B (feat): add admin order index page
  app/assets/stylesheets/application.tailwind.css
  app/assets/stylesheets/components/metrics.css
  app/controllers/admin/dashboard_controller.rb
  app/controllers/admin/orders_controller.rb
  app/models/order.rb
  app/views/admin/_header.html.erb
  app/views/admin/dashboard/index.html.erb
  app/views/admin/orders/_order.html.erb
  app/views/admin/orders/index.html.erb
  config/routes.rb
  spec/request/admin/dashboard_spec.rb
  spec/request/admin/orders_spec.rb
Labels: ruby, css

#179 STORM_B (feat): add basic email layout with SES AWS servise
  app/assets/images/home_img/white_logo.jpg
  app/mailers/application_mailer.rb
  app/views/layouts/mailer.html.erb
  config/credentials.yml.enc
  config/credentials/development.yml.enc
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/devise.rb
Labels: ruby, css

#180 STORM_B (feat): Update Ruby version from 3.1.3 to 3.2.2
  .github/workflows/rubyonrails.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  README.md
Labels: ruby

#183 Manual order
  app/assets/images/partials_img/google_icon.png
  app/assets/images/partials_img/instagram_icon.png
  app/assets/images/partials_img/messenger_icon.png
  app/assets/images/partials_img/paid_icon.png
  app/assets/images/partials_img/phone_icon.png
  app/assets/images/partials_img/telegram_icon.png
  app/assets/images/partials_img/unpaid_icon.png
  app/assets/images/partials_img/viber_icon.png
  app/assets/images/partials_img/whatsapp_icon.png
  app/controllers/dredd/dashboard_controller.rb
  app/controllers/dredd/manual_orders_controller.rb
  app/helpers/dredd/manual_order_helper.rb
  app/models/manual_order.rb
  app/views/dredd/_header.html.erb
  app/views/dredd/dashboard/all_orders.html.erb
  app/views/dredd/dashboard/index.html.erb
  app/views/dredd/feedback_calls/_feedback_call.html.erb
  app/views/dredd/manual_orders/_manual_order.html.erb
  app/views/dredd/manual_orders/index.html.erb
  app/views/dredd/orders/_order.html.erb
  config/routes.rb
  db/migrate/20230710095931_create_manual_order.rb
  db/schema.rb
  spec/factories/manual_orders.rb
  spec/models/manual_order_spec.rb
  spec/request/dredd/dashboard_spec.rb
  spec/request/dredd/manual_orders_spec.rb
  spec/request/dredd/orders_spec.rb
Labels: ruby

#184 STORM_B (feat): add phone lib gem, and update phone validation
  Gemfile
  Gemfile.lock
  app/models/feedback_call.rb
  config/initializers/phonelib.rb
  spec/request/dredd/dashboard_spec.rb
  spec/request/dredd/feedback_calls_spec.rb
  spec/request/static_pages_spec.rb
Labels: ruby

#185 Admin manual create
  app/assets/stylesheets/application.tailwind.css
  app/assets/stylesheets/components/select.css
  app/assets/stylesheets/components/typography.css
  app/controllers/dredd/manual_orders_controller.rb
  app/javascript/controllers/select_controller.js
  app/models/manual_order.rb
  app/views/devise/registrations/new.html.erb
  app/views/dredd/manual_orders/_form.html.erb
  app/views/dredd/manual_orders/_manual_order.html.erb
  app/views/dredd/manual_orders/new.html.erb
  app/views/dredd/product_categories/_errors.html.erb
  app/views/dredd/product_categories/_form.html.erb
  app/views/dredd/products/_form.html.erb
  app/views/dredd/shared/_errors.html.erb
  app/views/shared/_footer.html.erb
  config/routes.rb
  spec/factories/manual_orders.rb
  spec/request/dredd/dashboard_spec.rb
  spec/request/dredd/feedback_calls_spec.rb
  spec/request/dredd/manual_orders_spec.rb
  spec/request/static_pages_spec.rb
Labels: ruby, javascript, css

#188 STORM_B (feat): add google analytics to website
  app/helpers/google_analytics_helper.rb
  app/views/layouts/admin.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/checkout.html.erb
  spec/request/dredd/dashboard_spec.rb
Labels: ruby

#189 STORM_B (feat): add show action for show manual order
  app/helpers/dredd/manual_order_helper.rb
  app/views/dredd/manual_orders/_form.html.erb
  app/views/dredd/manual_orders/show.html.erb
  spec/helpers/dredd/manual_order_helper_spec.rb
  spec/request/dredd/manual_orders_spec.rb
Labels: ruby

#191 STORM_B (feat): updated view in admin dashboard
  app/controllers/dredd/dashboard_controller.rb
  app/controllers/dredd/manual_orders_controller.rb
  app/models/manual_order.rb
  app/views/dredd/_header.html.erb
  app/views/dredd/dashboard/all_orders.html.erb
  app/views/dredd/dashboard/index.html.erb
  app/views/dredd/manual_orders/_manual_order.html.erb
  config/routes.rb
  spec/request/dredd/dashboard_spec.rb
  spec/request/dredd/manual_orders_spec.rb
Labels: ruby

#193 STROM_B (feat) add S3 bucket creadentials for AWS S3
  Gemfile
  Gemfile.lock
  app/controllers/dredd/product_categories_controller.rb
  app/javascript/controllers/dropzone_controller.js
  app/models/product_category.rb
  app/views/dredd/product_categories/_form.html.erb
  config/configs/aws_config.rb
  config/credentials.yml.enc
  config/credentials/development.yml.enc
  config/environments/development.rb
  config/environments/production.rb
  config/storage.yml
Labels: ruby

#195 STROM_B (feat): add google auth to sign_in/up
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.tailwind.css
  app/controllers/users/omniauth_callbacks_controller.rb
  app/javascript/controllers/flash_controller.js
  app/models/user.rb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/dredd/shared/_flash.html.erb
  app/views/layouts/application.html.erb
  config/configs/google_config.rb
  config/credentials.yml.enc
  config/credentials/development.yml.enc
  config/initializers/devise.rb
  config/locales/devise.views.uk.yml
  config/routes.rb
  db/migrate/20230714210453_add_fields_to_user.rb
  db/schema.rb
Labels: ruby, javascript, css

#198 Partners section
  app/assets/images/partners/3dlab.svg
  app/assets/images/partners/black_mark.svg
  app/assets/images/partners/pps.svg
  app/assets/images/partners/printing_weekly.svg
  app/assets/images/partners/rc.svg
  app/assets/images/partners/sebco.svg
  app/assets/images/partners/stoliari.svg
  app/assets/images/partners/sygnis.svg
  app/assets/stylesheets/application.tailwind.css
  app/views/static_pages/_question_form.html.erb
  app/views/static_pages/home.html.erb
  config/locales/en/static_pages.en.yml
  config/locales/uk/static_pages.uk.yml
  tailwind.config.js
Labels: css

#202 STORM_B (feat): tailwind upgrade
  package.json
  tailwind.config.js
  yarn.lock
Labels: dependencies, css

#208 STORM_B (feat): add sentry to check errors in production
  Gemfile
  Gemfile.lock
  config/initializers/sentry.rb
Labels: ruby

#209 STORM_B (feat): add users page to admin panel
  app/controllers/dredd/users_controller.rb
  app/models/user.rb
  app/views/dredd/_header.html.erb
  app/views/dredd/users/_user.html.erb
  app/views/dredd/users/index.html.erb
  config/locales/en/dredd.en.yml
  config/locales/uk/dredd.uk.yml
  config/routes.rb
  spec/factories/users.rb
  spec/request/dredd/users_spec.rb
Labels: ruby

#211 Products count
  app/views/cart/_side_bar_cart.html.erb
  app/views/shared/_header.html.erb
Labels: css

#217 STORM_B (feat): add quality and infill to manual orders
  app/controllers/dredd/manual_orders_controller.rb
  app/views/dredd/manual_orders/_form.html.erb
  app/views/dredd/manual_orders/show.html.erb
  config/locales/en/dredd.en.yml
  config/locales/uk/dredd.uk.yml
  db/migrate/20230727074936_add_quality_and_infill_to_manual_orders.rb
  db/schema.rb
  spec/request/dredd/manual_orders_spec.rb
Labels: ruby

#216 Test select material
  app/assets/images/home_img/3d_print.png
  app/assets/images/home_img/3d_print.svg
  app/assets/images/home_img/modeling.png
  app/assets/images/home_img/print.png
  app/assets/images/home_img/rendering.png
  app/assets/images/icons_svg/3d_modeling_icon.svg
  app/assets/images/icons_svg/3d_printing_icon.svg
  app/assets/images/icons_svg/3d_rendering_icon.svg
  app/assets/images/icons_svg/dlp_printer.svg
  app/assets/images/icons_svg/fdm_printer.svg
  app/assets/images/icons_svg/printer.svg
  app/assets/images/icons_svg/sla_printer.svg
  app/controllers/prints_controller.rb
  app/controllers/static_pages_controller.rb
  app/helpers/printing_helper.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/selected_material_and_price_controller.js
  app/views/layouts/application.html.erb
  app/views/layouts/mailer.html.erb
  app/views/prints/show.html.erb
  app/views/shared/_header.html.erb
  app/views/static_pages/_question_form.html.erb
  app/views/static_pages/_upload_form.html.erb
  app/views/static_pages/home.html.erb
  app/views/static_pages/printing.html.erb
  app/views/static_pages/printing/_dlp_tab.html.erb
  app/views/static_pages/printing/_dlp_table_quality.html.erb
  app/views/static_pages/printing/_fdm_tab.html.erb
  app/views/static_pages/printing/_fdm_table_quality.html.erb
  app/views/static_pages/printing/_quality.html.erb
  app/views/static_pages/printing/_sla_tab.html.erb
  app/views/static_pages/printing/_sla_table_quality.html.erb
  config/locales/en/global.en.yml
  config/locales/en/static_pages.en.yml
  config/locales/uk/global.uk.yml
  config/locales/uk/static_pages.uk.yml
  config/routes.rb
Labels: ruby, javascript, WIP

#218 STROM_B (feat): add modeling, rendering, and printing pages to produc…
  app/assets/images/print_img/arm_modeling.png
  app/assets/images/print_img/arm_printing.png
  app/assets/images/print_img/arm_rendering.png
  app/controllers/static_pages_controller.rb
  app/views/shared/_header.html.erb
  app/views/static_pages/home.html.erb
  app/views/static_pages/modeling.html.erb
  app/views/static_pages/printing.html.erb
  app/views/static_pages/rendering.html.erb
  config/locales/en/global.en.yml
  config/locales/en/static_pages.en.yml
  config/locales/uk/global.uk.yml
  config/locales/uk/static_pages.uk.yml
  config/routes.rb
  spec/request/static_pages_spec.rb
Labels: ruby

#219 STORM_B (feat): add 3D orders to admin page
  app/controllers/dredd/dashboard_controller.rb
  app/controllers/dredd/modeling_orders_controller.rb
  app/controllers/dredd/printing_orders_controller.rb
  app/controllers/dredd/rendering_orders_controller.rb
  app/controllers/modeling_orders_controller.rb
  app/controllers/printing_orders_controller.rb
  app/controllers/rendering_orders_controller.rb
  app/controllers/static_pages_controller.rb
  app/models/modeling_order.rb
  app/models/printing_order.rb
  app/models/rendering_order.rb
  app/views/dredd/_header.html.erb
  app/views/dredd/dashboard/index.html.erb
  app/views/dredd/modeling_orders/_modeling_order.html.erb
  app/views/dredd/modeling_orders/index.html.erb
  app/views/dredd/printing_orders/_printing_order.html.erb
  app/views/dredd/printing_orders/index.html.erb
  app/views/dredd/rendering_orders/_rendering_order.html.erb
  app/views/dredd/rendering_orders/index.html.erb
  app/views/modeling_orders/index.html.erb
  app/views/printing_orders/index.html.erb
  app/views/rendering_orders/index.html.erb
  app/views/shared/_upload_form.html.erb
  config/locales/en/dredd.en.yml
  config/locales/en/static_pages.en.yml
  config/locales/uk/dredd.uk.yml
  config/locales/uk/static_pages.uk.yml
  config/routes.rb
  db/migrate/20230728130920_create_modeling_order.rb
  db/migrate/20230728130934_create_rendering_order.rb
  db/migrate/20230728130947_create_printing_order.rb
  db/schema.rb
  spec/factories/modeling_order.rb
  spec/factories/printing_order.rb
  spec/factories/rendering_order.rb
  spec/request/dredd/dashboard_spec.rb
  spec/request/dredd/modeling_spec.rb
  spec/request/dredd/printing_spec.rb
  spec/request/dredd/rendering_spec.rb
  spec/request/static_pages_spec.rb
Labels: ruby
