Repository Shabaldas/storm_esbuild, pull requests merged in 2023-09, with the labels that each got.

#262 STORM_B (feat): add modeller to manual orders
  app/controllers/dredd/manual_orders_controller.rb
  app/lib/database_seeds/dummy/manual_orders_seed.rb
  app/models/manual_order.rb
  app/views/dredd/manual_orders/_form.html.erb
  config/locales/en/dredd.en.yml
  config/locales/uk/dredd.uk.yml
  db/migrate/20230910111735_add_modeller_to_manual_order.rb
  db/schema.rb
  package.json
  spec/factories/manual_orders.rb
  spec/helpers/dredd/manual_order_helper_spec.rb
  spec/lib/database_seeds/dummy/manual_orders_seed_spec.rb
  spec/request/dredd/manual_orders_spec.rb
  yarn.lock
Labels: ruby

#264 Portfolio section
  app/assets/images/icons_svg/arrow-thick-left.svg
  app/assets/images/icons_svg/arrow-thick-right.svg
  app/assets/images/icons_svg/arrow-thin-left.svg
  app/assets/images/icons_svg/arrow-thin-right.svg
  app/assets/images/icons_svg/arrows-pointing-out.svg
  app/assets/images/icons_svg/print-label.svg
  app/assets/stylesheets/application.tailwind.css
  app/controllers/dredd/portfolios_controller.rb
  app/controllers/modeling_orders_controller.rb
  app/controllers/printing_orders_controller.rb
  app/controllers/rendering_orders_controller.rb
  app/javascript/controllers/carousel_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/lightbox_controller.js
  app/models/portfolio.rb
  app/views/dredd/_header.html.erb
  app/views/dredd/portfolios/_form.html.erb
  app/views/dredd/portfolios/_portfolio.html.erb
  app/views/dredd/portfolios/edit.html.erb
  app/views/dredd/portfolios/index.html.erb
  app/views/dredd/portfolios/new.html.erb
  app/views/modeling_orders/index.html.erb
  app/views/printing_orders/index.html.erb
  app/views/rendering_orders/index.html.erb
  app/views/shared/_portfolio.html.erb
  config/locales/en/dredd.en.yml
  config/locales/en/static_pages.en.yml
  config/locales/uk/dredd.uk.yml
  config/locales/uk/static_pages.uk.yml
  config/routes.rb
  db/migrate/20230914161423_create_portfolio.rb
  db/schema.rb
  package.json
  spec/factories/portfolios.rb
  spec/models/portfolio_spec.rb
  spec/request/dredd/dashboard_spec.rb
  spec/request/dredd/portfolios_spec.rb
  spec/request/dredd/users_spec.rb
  spec/request/modeling_spec.rb
  spec/request/printing_spec.rb
  spec/request/rendering_spec.rb
  yarn.lock
Labels: ruby, javascript, css

#270 STORM_B (feat): add bullet gem configs, with query optimizations
  app/controllers/dredd/portfolios_controller.rb
  app/controllers/modeling_orders_controller.rb
  app/controllers/printing_orders_controller.rb
  app/controllers/rendering_orders_controller.rb
  config/environments/development.rb
  config/environments/test.rb
Labels: ruby

#274 Accounting
  app/assets/stylesheets/components/metrics.css
  app/controllers/dredd/accountings_controller.rb
  app/views/dredd/_header.html.erb
  app/views/dredd/accountings/_accounting_data.html.erb
  app/views/dredd/accountings/index.html.erb
  app/views/dredd/accountings/monthly.html.erb
  app/views/dredd/dashboard/index.html.erb
  config/locales/en/dredd.en.yml
  config/locales/en/global.en.yml
  config/locales/uk/dredd.uk.yml
  config/locales/uk/global.uk.yml
  config/routes.rb
  spec/request/dredd/dashboard_spec.rb
Labels: ruby, css

#285 STORM_B (feat): add sidekiq worker to project
  .DS_Store
  .env
  Gemfile
  Gemfile.lock
  Procfile
  Procfile.dev
  app/jobs/test_job.rb
  bin/sidekiq
  bin/sidekiqmon
  config/application.rb
  config/configs/sidekiq_config.rb
  config/credentials.yml.enc
  config/credentials/development.yml.enc
  config/initializers/sidekiq.rb
  config/routes.rb
  config/schedule.yml
  spec/rails_helper.rb
Labels: ruby

#289 STORM_B (feat): add end date to manual orders
  app/controllers/dredd/accountings_controller.rb
  app/controllers/dredd/manual_orders_controller.rb
  app/views/dredd/accountings/monthly.html.erb
  app/views/dredd/manual_orders/_form.html.erb
  config/locales/en/dredd.en.yml
  config/locales/uk/dredd.uk.yml
  config/schedule.yml
  db/migrate/20230929155428_add_end_date_to_manual_orders.rb
  db/schema.rb
  spec/request/dredd/manual_orders_spec.rb
Labels: ruby
