Repository Shabaldas/storm_esbuild, pull requests merged in 2024-02, with the labels that each got.

#250 STORM_B (feat): add city model, and custom printing city page
  Gemfile
  Gemfile.lock
  app/controllers/concerns/cities_detector.rb
  app/controllers/printing_orders_controller.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/scroll_to_controller.js
  app/lib/database_seeds/main.rb
  app/lib/database_seeds/real/cities_seed.rb
  app/models/city.rb
  app/views/printing_orders/_printing_page.html.erb
  app/views/printing_orders/index.html.erb
  app/views/printing_orders/printing_in_your_city.html.erb
  config/locales/en/static_pages.en.yml
  config/locales/uk/static_pages.uk.yml
  config/routes.rb
  db/migrate/20230820144901_create_cities.rb
  db/schema.rb
  package.json
  spec/factories/cities.rb
  spec/lib/database_seeds/real/cities_seed_spec.rb
  spec/request/printing_spec.rb
  yarn.lock
Labels: WIP

#414 (feat): add west regions cities to DB
  app/lib/database_seeds/main.rb
  app/lib/database_seeds/real/cities_seed.rb
  spec/lib/database_seeds/real/cities_seed_spec.rb
Labels: ruby

#417 STORM_F: fix description width & title line break
  app/assets/stylesheets/application.tailwind.css
  app/views/modeling_orders/index.html.erb
  app/views/modeling_orders/lazy_index.html.erb
  app/views/modeling_orders/modeling_in_your_city.html.erb
  app/views/printing_orders/index.html.erb
  app/views/printing_orders/printing_in_your_city.html.erb
  app/views/rendering_orders/index.html.erb
  app/views/rendering_orders/lazy.html.erb
  app/views/rendering_orders/rendering_in_your_city.html.erb
Labels: css

#456 STORM_B (feat): add paper_trail gem
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/client.rb
  app/models/manual_order.rb
  app/models/product.rb
  app/models/user.rb
  db/migrate/20240224113618_create_versions.rb
  db/schema.rb
Labels: ruby

#458 STORM_F (feat): add password visibility, and textarea autogrow
  app/javascript/controllers/index.js
  app/views/dredd/costs/_form.html.erb
  app/views/dredd/manual_orders/_form.html.erb
  app/views/dredd/modeling_orders/_form.html.erb
  app/views/dredd/printers/_form.html.erb
  app/views/dredd/printing_orders/_form.html.erb
  app/views/dredd/product_categories/_form.html.erb
  app/views/dredd/products/_form.html.erb
  app/views/dredd/rendering_orders/_form.html.erb
  app/views/profiles/edit_password.html.erb
  app/views/shared/_upload_form.html.erb
  package.json
  yarn.lock
Labels: ruby, javascript
